export const REQUEST_SERIES = 'REQUEST_SERIES';
export const GET_SERIES = 'GET_SERIES';

export const REQUEST_SERIES_DETAIL = 'REQUEST_SERIES_DETAIL';
export const GET_SERIES_DETAIL = 'GET_SERIES_DETAIL';
