export const SHOW_LOADING = 'SHOW_LOADING';
export const SHOW_ERROR = 'SHOW_ERROR';

export const REQUEST_LIST_MOVIES = 'REQUEST_LIST_MOVIES';
export const SHOW_LIST_MOVIES = 'SHOW_LIST_MOVIES';

export const REQUEST_GENRES_MOVIES = 'REQUEST_GENRES_MOVIES';
export const SHOW_GENRES_MOVIES = 'SHOW_GENRES_MOVIES';

export const REQUEST_SEARCH_MOVIES = 'REQUEST_SEARCH_MOVIES';
export const SHOW_SEARCH_MOVIES = 'SHOW_SEARCH_MOVIES';

export const REQUEST_MOVIE_DETAIL = 'REQUEST_MOVIE_DETAIL';
export const GET_MOVIE_DETAIL = 'GET_MOVIE_DETAIL';

export const SHOW_NEXT_PAGE = 'SHOW_NEXT_PAGE';
export const SHOW_PREV_PAGE = 'SHOW_PREV_PAGE';
